# Generated by Django 4.1.1 on 2022-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_skill_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(to='website.skill'),
        ),
    ]
